name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: miermontoto/waka-readme-stats@v5
        with:
          WAKATIME_API_KEY: ${{ waka_7fddba0f-2340-4291-8ef9-0270f6800f06 }}
          GH_TOKEN: ${{ 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 }}
